version: 1
game_engine: gbx-custom
tag_space: 64M
extend_limits: true
scenarios:
  - alpha_firefight/levels/alpha_halo/alpha_halo_dev
commands:
  release:
    - mercury build --release --output package/game-maps/
  symlinks:
  - ln -f -s "$PWD/dist/alpha_halo.lua" "$HALO_CE_DATA_PATH/chimera/lua/scripts/map/alpha_halo_dev.lua"